package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"

	"github.com/morzecrew/morzer/internal/cli"
)

// The generated command index: one page listing every command in the tree with
// the reference section that documents it.
//
// It exists because `docs-check` already proved every command is *mentioned*
// somewhere, which is coverage without a table of contents: the surface is
// spread over five reference pages that carry no index between them, so an
// operator who knows a command exists still has to guess which page it is on.
//
// Generated rather than written, and generated *here* rather than by a second
// binary, because the point is that the index and the coverage check walk the
// same set. Two tools would be two walks, and the day they disagreed the index
// would be missing exactly the command nothing had noticed was undocumented.
// `just docs-index` writes it; `just docs-check` regenerates it in memory and
// fails on any difference -- the same generate-commit-check pattern the JSON
// schemas already use.

// indexPage is the generated page, relative to the docs root.
const indexPage = "reference/index.md"

// indexMarker opens the generated file. It is the first thing a reader meets
// and the first thing an editor meets, which is the only defence a generated
// file in a docs tree has against being edited by hand.
const indexMarker = "<!-- Generated by `just docs-index`. Edit the command's `Short` string, not this file. -->"

// referencePage says which page documents each top-level command, and
// optionally which section of it.
//
// The one thing here a machine cannot derive: `config` is documented on the
// parameters page because parameters are what it changes, and `ls` on the
// installation page because that is where the machine's installations are
// described. Neither page has a heading named after the command, so both carry
// a fragment -- and both fragments are checked against the page's real
// headings, so this map cannot point at a section that has been renamed away.
//
// A top-level command missing from this map fails the build rather than being
// dropped from the index: a command nobody assigned a page to is a command
// whose documentation nobody decided on, and the index quietly omitting it is
// how it would stay that way.
var referencePage = map[string]string{
	"init":         "reference/commands.md",
	"apply":        "reference/commands.md",
	"status":       "reference/commands.md",
	"update":       "reference/commands.md",
	"rollback":     "reference/commands.md",
	"doctor":       "reference/commands.md",
	"logs":         "reference/commands.md",
	"ps":           "reference/commands.md",
	"stats":        "reference/commands.md",
	"exec":         "reference/commands.md",
	"backup":       "reference/commands.md",
	"restore":      "reference/commands.md",
	"version":      "reference/commands.md",
	"config":       "reference/parameters.md#changing-one-after-install",
	"secret":       "reference/secret-commands.md",
	"release":      "reference/release-commands.md",
	"installation": "reference/installation-commands.md",
	// The attestations page documents the artifact and the command that
	// reads it back, because the two are unusable apart: the command's
	// whole output is verdicts about that document's fields.
	"attest":     "reference/attestations.md",
	"ls":         "reference/installation-commands.md#installation-list",
	"completion": "reference/commands.md#completion-install",
}

// indexEntry is one row.
type indexEntry struct {
	// Path is the command as an operator types it, without the program
	// name: "release prune".
	Path string
	// Aliases are the other names for this command at the same level. They
	// share the row rather than getting one of their own -- `config ls` is
	// not a second command, and a table that said it was would report a
	// surface larger than the one that exists.
	Aliases []string

	Short string

	// Page and Anchor are where the reference for this command lives.
	Page   string
	Anchor string
}

// walkCommands calls visit for every command this project documents.
//
// One walk, used by the index and by the coverage check, so the two cannot
// validate different sets. What is excluded is exactly what the project does
// not own: cobra's own `help` and `completion`, which cli.IsGenerated answers
// from the scope annotation rather than from a list of names -- `completion
// install` is this project's and is included, which a name check would have
// dropped from both the index and coverage without saying so. Hidden commands
// go too: `--root` exists for the test suite, and a generated page naming it
// would undo the decision to keep it out of `--help`.
func walkCommands(root *cobra.Command, visit func(path []string, cmd *cobra.Command)) {
	var walk func(cmd *cobra.Command, path []string)
	walk = func(cmd *cobra.Command, path []string) {
		for _, sub := range cmd.Commands() {
			// Hidden prunes the subtree; generated does not.
			// Cobra's `completion` is not documented and its
			// `install` subcommand is, so the walk descends past
			// what it does not visit.
			if sub.Hidden {
				continue
			}
			full := append(append([]string(nil), path...), strings.Fields(sub.Use)[0])
			if !cli.IsGenerated(sub) {
				visit(full, sub)
			}
			walk(sub, full)
		}
	}
	walk(root, nil)
}

// commandEntries builds every row, resolving each command's reference target.
//
// A row's anchor is the most specific heading that exists for the command or
// for one of its ancestors, falling back to the page's own title. That is the
// honest reading of "where do I go to read about this": `backup target add` is
// documented inside the `backup target` section, and pointing at it beats
// inventing an anchor no page has.
func commandEntries(root *cobra.Command, pages []page) ([]indexEntry, []string) {
	headings := map[string]map[string]bool{}
	for _, p := range pages {
		headings[p.Rel] = anchorsIn(p.Prose)
	}

	var entries []indexEntry
	var problems []string

	walkCommands(root, func(path []string, cmd *cobra.Command) {
		joined := strings.Join(path, " ")

		declared, ok := referencePage[path[0]]
		if !ok {
			problems = append(problems, fmt.Sprintf(
				"`morzer %s` has no reference page: add `%s` to referencePage "+
					"in tools/docscheck/cmdindex.go", joined, path[0]))
			return
		}
		target, fallback, _ := strings.Cut(declared, "#")

		anchors, ok := headings[target]
		if !ok {
			problems = append(problems, fmt.Sprintf(
				"`morzer %s` points at %s, which is not a page", joined, target))
			return
		}
		if fallback != "" && !anchors[fallback] {
			problems = append(problems, fmt.Sprintf(
				"`morzer %s` points at %s#%s, and that page has no such heading",
				joined, target, fallback))
			return
		}

		// The most specific heading that exists for this command or for
		// one of its ancestors: `backup target add` is documented inside
		// the `backup target` section, and pointing at it beats
		// inventing an anchor no page has.
		anchor := ""
		for i := len(path); i > 0 && anchor == ""; i-- {
			if candidate := slug(strings.Join(path[:i], " ")); anchors[candidate] {
				anchor = candidate
			}
		}
		switch {
		case anchor != "":
		case fallback != "":
			anchor = fallback
		default:
			// The page's own title, which every page has. Reaching
			// here means the page documents this command without a
			// section of its own, which is a routing answer rather
			// than a fault.
			anchor = pageTitleAnchor(pages, target)
		}

		entries = append(entries, indexEntry{
			Path: joined, Aliases: cmd.Aliases, Short: cmd.Short,
			Page: target, Anchor: anchor,
		})
	})

	sort.Strings(problems)
	return entries, problems
}

var headingRe = regexp.MustCompile(`(?m)^#{1,6}\s+(.+?)\s*$`)

// anchorsIn collects the anchors a page's headings produce.
func anchorsIn(prose string) map[string]bool {
	out := map[string]bool{}
	for _, m := range headingRe.FindAllStringSubmatch(prose, -1) {
		out[slug(m[1])] = true
	}
	return out
}

// pageTitleAnchor is the anchor of a page's first heading.
func pageTitleAnchor(pages []page, rel string) string {
	for _, p := range pages {
		if p.Rel != rel {
			continue
		}
		if m := headingRe.FindStringSubmatch(p.Prose); m != nil {
			return slug(m[1])
		}
	}
	return ""
}

var slugDrop = regexp.MustCompile(`[^a-z0-9 -]`)

// slug turns a heading into the anchor a Markdown renderer gives it:
// lowercased, punctuation dropped, spaces to hyphens.
func slug(s string) string {
	s = strings.ToLower(strings.TrimSpace(s))
	s = strings.ReplaceAll(s, "`", "")
	s = slugDrop.ReplaceAllString(s, "")
	return strings.ReplaceAll(strings.Join(strings.Fields(s), " "), " ", "-")
}

// renderIndex writes the page.
func renderIndex(entries []indexEntry) string {
	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString("title: Every command\n")
	b.WriteString("icon: lucide/list\n")
	b.WriteString("summary: Every command morzer has, what it does, and which reference page documents it\n")
	b.WriteString("---\n\n")
	b.WriteString(indexMarker + "\n\n")
	b.WriteString("# Every command\n\n")
	b.WriteString("Generated from the command tree, so a command cannot exist without a row\n")
	b.WriteString("here. The reference column points at the section that documents it; the\n")
	b.WriteString("`Short` text is the command's own, as `morzer --help` prints it.\n\n")
	b.WriteString("| Command | What it does | Reference |\n")
	b.WriteString("| --- | --- | --- |\n")

	for _, e := range entries {
		command := "`morzer " + e.Path + "`"
		if len(e.Aliases) > 0 {
			aliased := make([]string, 0, len(e.Aliases))
			for _, a := range e.Aliases {
				aliased = append(aliased, "`"+a+"`")
			}
			command += " (also " + strings.Join(aliased, ", ") + ")"
		}

		// Relative to this page, which sits in the same directory as
		// every page it links to.
		href := strings.TrimPrefix(e.Page, "reference/")
		if e.Anchor != "" {
			href += "#" + e.Anchor
		}
		name := strings.TrimSuffix(strings.TrimPrefix(e.Page, "reference/"), ".md")

		fmt.Fprintf(&b, "| %s | %s | [%s](%s) |\n", command, e.Short, name, href)
	}
	return b.String()
}

// checkCommandIndex fails when the committed page is not what the tree
// produces now.
func checkCommandIndex(rep *report, root string, pages []page) {
	rep.checks++

	entries, problems := commandEntries(cli.CommandTree(), pages)
	for _, p := range problems {
		rep.add("command index", "%s", p)
	}

	want := renderIndex(entries)
	path := filepath.Join(root, docsDir, filepath.FromSlash(indexPage))

	got, err := os.ReadFile(path)
	if err != nil {
		rep.add("command index", "%s cannot be read: %v — run `just docs-index`", indexPage, err)
		return
	}
	if string(got) != want {
		rep.add("command index",
			"%s is not what the command tree produces — run `just docs-index`", indexPage)
	}
}

// writeCommandIndex regenerates the page.
func writeCommandIndex(root string, pages []page) error {
	entries, problems := commandEntries(cli.CommandTree(), pages)
	if len(problems) > 0 {
		return fmt.Errorf("cannot generate %s:\n  - %s",
			indexPage, strings.Join(problems, "\n  - "))
	}

	path := filepath.Join(root, docsDir, filepath.FromSlash(indexPage))
	if err := os.WriteFile(path, []byte(renderIndex(entries)), 0o644); err != nil {
		return err
	}
	fmt.Printf("docs-index: %d command(s) written to %s\n", len(entries), indexPage)
	return nil
}
