package main

// The support bundle's component page (RFC 0024 P1).
//
// Decision 2 makes the inventory an ABI: it may grow, and it may only shrink
// with a version bump. An ABI maintained by hand beside the code that
// implements it is an ABI that drifts, and this one drifts in the direction
// that matters -- a page claiming the age identity is never included, beside
// code that started including it, is worse than no page at all.
//
// So the page is generated from `domain.SupportInventory` exactly as
// `reference/index.md` is generated from the command tree, by the same binary
// and the same `just docs-index`. The check half fails the build when the
// committed page is not what the table produces now.

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/morzecrew/morzer/internal/domain"
)

const supportPage = "reference/support-bundle.md"

const supportMarker = "<!-- Generated by `just docs-index` from domain.SupportInventory. " +
	"Edit the inventory, not this file. -->"

// renderSupportInventory writes the page.
//
// Three tables rather than one with a class column, because the question an
// operator brings to this page is "is X in there", and the answer they need
// first is the refusal list. A single sortable table would make them read
// eighteen rows to find out.
func renderSupportInventory() string {
	var b strings.Builder

	b.WriteString("---\n")
	b.WriteString("title: What a support bundle contains\n")
	b.WriteString("icon: lucide/package\n")
	b.WriteString("summary: Every component `morzer support bundle` collects, " +
		"every component it refuses, and why each is classified that way\n")
	b.WriteString("---\n\n")
	b.WriteString(supportMarker + "\n\n")
	b.WriteString("# What a support bundle contains\n\n")

	b.WriteString("`morzer support bundle` writes one archive you can hand to a stranger.\n")
	b.WriteString("This page is that archive's contract. It is generated from the inventory in\n")
	b.WriteString("the code, so nothing can be collected without a row here.\n\n")

	b.WriteString("The list may grow. It may only **shrink** with a version bump: an operator\n")
	b.WriteString("who has read it once will not read it again, and a component quietly\n")
	b.WriteString("removed is a promise quietly broken in the direction of \"we sent less than\n")
	b.WriteString("you thought\" — which is the harmless direction only until somebody is\n")
	b.WriteString("debugging from an archive that no longer has what they need.\n\n")

	b.WriteString("## Never included\n\n")
	b.WriteString("Read this first. Inclusion is an allowlist, so these are excluded by not\n")
	b.WriteString("being listed — they are named anyway, because \"is the age identity in\n")
	b.WriteString("there?\" deserves an answer somebody can check rather than a promise.\n")
	b.WriteString("Adding a collector for one of these fails the build.\n\n")
	writeSupportTable(&b, domain.SupportNever, "What")

	b.WriteString("\n## Included\n\n")
	b.WriteString("Every one of these is produced by the manager and already structured. No\n")
	b.WriteString("part of it is raw output from your product.\n\n")
	writeSupportTable(&b, domain.SupportInclude, "File")

	b.WriteString("\n## Included after redaction\n\n")
	b.WriteString("The only raw bytes from your containers in the archive, and the only\n")
	b.WriteString("component whose safety depends on the redactor rather than on its shape.\n\n")
	writeSupportTable(&b, domain.SupportRedact, "File")

	b.WriteString("\n## What redaction actually promises\n\n")
	b.WriteString("**Every** component is scrubbed on its way into the archive, not only the\n")
	b.WriteString("one classified above. The class says where a component's bytes came\n")
	b.WriteString("from; redaction is about *when* they were written, and most of these\n")
	b.WriteString("were written long before you ran this command. The journal is the clear\n")
	b.WriteString("case: it is appended to across every operation this installation has\n")
	b.WriteString("ever run, and a message that embedded a secret was written at a moment\n")
	b.WriteString("the manager may not have known that secret yet.\n\n")
	b.WriteString("`meta.json` records how many values were replaced in each file. A count\n")
	b.WriteString("of zero is **not** proof that a file was clean — it is proof that no\n")
	b.WriteString("value this installation currently holds appeared in it, which is a\n")
	b.WriteString("smaller claim. A secret that was rotated away, or one that was never\n")
	b.WriteString("declared to the manager at all, is not something it can recognise.\n\n")
	b.WriteString("Container logs are the exception that is enforced rather than promised:\n")
	b.WriteString("if the secret values cannot be loaded, they are left out of the archive\n")
	b.WriteString("entirely and `meta.json` says so. Everything else still ships.\n")

	b.WriteString("\n## Before you send one\n\n")
	b.WriteString("Run `morzer support bundle` with `--preview`. It writes nothing and prints\n")
	b.WriteString("the same component list with per-file sizes and redaction counts, so you can\n")
	b.WriteString("see what would leave this machine before anything does. It is the same\n")
	b.WriteString("table either way — one rendering, so the preview and the archive cannot\n")
	b.WriteString("disagree about what was collected.\n\n")
	b.WriteString("`--dir` writes the archive somewhere other than the working directory.\n")
	b.WriteString("There is no flag that disables redaction. A flag like that becomes the\n")
	b.WriteString("one every support article tells you to pass, and then redaction is a\n")
	b.WriteString("feature nobody uses; if you genuinely need unredacted output, `morzer\n")
	b.WriteString("logs --no-redact` makes that choice one file at a time.\n")

	return b.String()
}

// writeSupportTable renders one class.
func writeSupportTable(b *strings.Builder, class domain.SupportClass, firstColumn string) {
	fmt.Fprintf(b, "| %s | Component | Why |\n| --- | --- | --- |\n", firstColumn)

	for _, c := range domain.SupportComponents(class) {
		first := "—"
		if c.Name != "" {
			first = "`" + c.Name + "`"
		}
		fmt.Fprintf(b, "| %s | %s | %s |\n", first, c.Title, c.Reason)
	}
}

// checkSupportInventory fails when the committed page is not what the inventory
// produces now.
func checkSupportInventory(rep *report, root string) {
	rep.checks++

	path := filepath.Join(root, docsDir, filepath.FromSlash(supportPage))
	got, err := os.ReadFile(path)
	if err != nil {
		rep.add("support inventory",
			"%s cannot be read: %v — run `just docs-index`", supportPage, err)
		return
	}
	if string(got) != renderSupportInventory() {
		rep.add("support inventory",
			"%s is not what domain.SupportInventory produces — run `just docs-index`", supportPage)
	}
}

// writeSupportInventory regenerates the page.
func writeSupportInventory(root string) error {
	path := filepath.Join(root, docsDir, filepath.FromSlash(supportPage))
	if err := os.WriteFile(path, []byte(renderSupportInventory()), 0o644); err != nil {
		return err
	}
	fmt.Printf("docs-index: %d support component(s) written to %s\n",
		len(domain.SupportInventory), supportPage)
	return nil
}
