package clitest_test

import (
	"strings"
	"testing"

	"github.com/morzecrew/morzer/test/clitest"
)

// Everything a secret command does is bounded by one rule: the value never
// leaves the encrypted state except into tmpfs. So every test here checks the
// command did its job *and* that the value is nowhere in what it printed.

const dbPassword = "a-real-database-password-nobody-should-see"

func TestSecretSetTakesTheValueFromStdinAndPrintsNone(t *testing.T) {
	r := clitest.NewInstalled(t)

	out := r.RunWithInput(dbPassword+"\n", "secret", "set", "db_password")
	out.ExitCode(0)
	out.NoOutputContains(dbPassword)

	// It is really stored, and `list` shows a fingerprint rather than a
	// value -- in every output mode.
	list := r.Run("secret", "list").ExitCode(0)
	list.StdoutContains("db_password")
	list.NoOutputContains(dbPassword)

	asJSON := r.Run("secret", "list", "--json").ExitCode(0)
	asJSON.NoOutputContains(dbPassword)
}

func TestSecretSetRefusesAnEmptyValue(t *testing.T) {
	r := clitest.NewInstalled(t)

	// An empty pipe is how a mistyped `cat` reaches this, and storing the
	// empty string would make the next apply fail somewhere else entirely.
	out := r.RunWithInput("", "secret", "set", "db_password")
	out.Failed().OutputContains("empty")
	out.OutputContains("secret remove")
}

func TestSecretGenerate(t *testing.T) {
	r := clitest.NewInstalled(t)

	// `init --generate-secrets` already made every secret the release
	// declares a generator for, so generating one again is refused --
	// silently replacing a live credential is what `rotate` is for, and it
	// says so.
	existing := r.Run("secret", "generate", "db_password")
	existing.Failed().OutputContains("already exists")
	existing.OutputContains("secret rotate")

	// A secret the release says nothing about needs the shape given.
	r.Run("secret", "generate", "extra_token", "--kind", "hex", "--length", "32").
		ExitCode(0)
	r.Run("secret", "list").ExitCode(0).StdoutContains("extra_token")
}

func TestSecretGenerateRefusesAKindNobodyDefined(t *testing.T) {
	r := clitest.NewInstalled(t)

	r.Run("secret", "generate", "x", "--kind", "runes").Failed().
		OutputContains("runes")
}

func TestSecretRotateProducesADifferentValue(t *testing.T) {
	r := clitest.NewInstalled(t).SetSecret("db_password", dbPassword)

	before := fingerprint(t, r, "db_password")
	r.Run("secret", "rotate", "db_password").ExitCode(0)
	after := fingerprint(t, r, "db_password")

	if before == after {
		t.Errorf("rotating produced the same fingerprint (%s), so the credential "+
			"an operator believes they replaced is the one that leaked", before)
	}
}

// TestSecretRemoveRefusesWhatTheReleaseRequires. Removing it would make the
// next `apply` fail, somewhere else, later.
func TestSecretRemoveRefusesWhatTheReleaseRequires(t *testing.T) {
	r := clitest.NewInstalled(t).SetSecret("db_password", dbPassword)

	out := r.Run("secret", "remove", "db_password")
	out.Failed().OutputContains("required by the installed release")
	out.OutputContains("--force")

	// Still there.
	r.Run("secret", "list").ExitCode(0).StdoutContains("db_password")

	// And --force is the operator saying they mean it.
	r.Run("secret", "remove", "db_password", "--force").ExitCode(0)
	r.Run("secret", "list").ExitCode(0).NoOutputContains("db_password")
}

func TestSecretRemoveOfSomethingOptional(t *testing.T) {
	r := clitest.NewInstalled(t).SetSecret("smtp_password", "an-optional-value")

	r.Run("secret", "remove", "smtp_password").ExitCode(0)
	r.Run("secret", "list").ExitCode(0).NoOutputContains("smtp_password")
}

func TestSecretRecipients(t *testing.T) {
	r := clitest.NewInstalled(t)

	// The machine's own key is there from `init`, and is identified as
	// such so the removal guard below has something to refuse.
	list := r.Run("secret", "recipients", "list").ExitCode(0)
	list.StdoutContains("age1")

	asJSON := r.Run("secret", "recipients", "list", "--json").ExitCode(0)
	asJSON.Field("data")
}

func TestSecretRecipientsAddAndRemove(t *testing.T) {
	r := clitest.NewInstalled(t)

	// A key generated by the tool itself, so the test does not depend on a
	// constant that age might one day reject.
	keyPath := r.Path("recovery.key")
	gen := r.Run("secret", "recipients", "generate-recovery-key", keyPath)
	gen.ExitCode(0)

	pub := extractAgeKey(t, gen.Stdout+gen.Stderr)
	if pub == "" {
		t.Fatalf("the generated public key was not printed:\n%s\n%s", gen.Stdout, gen.Stderr)
	}

	// Generating a key does not grant it access. That is two decisions --
	// "make me an offline key" and "let it read this state" -- and running
	// them together would mean a key written to the wrong path silently
	// became a recipient of everything.
	r.Run("secret", "recipients", "list").ExitCode(0).NoOutputContains(pub)

	r.Run("secret", "recipients", "add", pub, "--kind", "recovery").ExitCode(0)
	r.Run("secret", "recipients", "list").ExitCode(0).StdoutContains(pub)

	r.Run("secret", "recipients", "remove", pub).ExitCode(0)
	r.Run("secret", "recipients", "list").ExitCode(0).NoOutputContains(pub)
}

// TestSecretRecipientsRefusesRemovingTheMachineKey. Removing it locks the
// manager out of its own secret state, and the operator would not discover it
// until the next apply -- possibly after a reboot, with the product down.
func TestSecretRecipientsRefusesRemovingTheMachineKey(t *testing.T) {
	r := clitest.NewInstalled(t)

	list := r.Run("secret", "recipients", "list").ExitCode(0)
	machine := extractAgeKey(t, list.Stdout)
	if machine == "" {
		t.Fatalf("no recipient was listed:\n%s", list.Stdout)
	}

	out := r.Run("secret", "recipients", "remove", machine)
	out.Failed().OutputContains("own recipient key")
	out.OutputContains("lock the manager out")
}

func TestSecretRenderWritesToTmpfsAtFourHundred(t *testing.T) {
	r := clitest.NewInstalled(t).
		SetSecret("db_password", dbPassword).
		SetSecret("session_key", "a-session-key-value")

	out := r.Run("secret", "render").ExitCode(0)
	out.StdoutContains("db_password", "0400")
	out.NoOutputContains(dbPassword)
}

// TestSecretCommandsOnAMachineWithNoInstallation records which of them are
// questions and which are actions.
//
// Asking what is there before anything is there is a legitimate question with
// the answer "nothing" -- refusing it would make `secret list` unusable as the
// first thing anybody types. Changing something that does not exist is not.
func TestSecretCommandsOnAMachineWithNoInstallation(t *testing.T) {
	r := clitest.New(t)

	t.Run("the questions answer emptily", func(t *testing.T) {
		r.Run("secret", "list").ExitCode(0).StdoutContains("no secrets")
		r.Run("secret", "recipients", "list").ExitCode(0)
	})

	t.Run("rendering refuses, because there is no release to render for", func(t *testing.T) {
		r.Run("secret", "render").Failed()
	})

	t.Run("removing what is not there is a no-op, not a refusal", func(t *testing.T) {
		// Delete is idempotent: the state afterwards is the state the
		// operator asked for either way, and refusing would make a
		// clean-up script fail on its second run.
		r.Run("secret", "remove", "db_password").ExitCode(0)
	})
}

func fingerprint(t *testing.T, r *clitest.Runner, name string) string {
	t.Helper()

	out := r.Run("secret", "list").ExitCode(0)
	for _, line := range strings.Split(out.Stdout, "\n") {
		if strings.HasPrefix(line, name) {
			fields := strings.Fields(line)
			if len(fields) < 2 {
				t.Fatalf("the list line for %s has no fingerprint: %q", name, line)
			}
			return fields[1]
		}
	}
	t.Fatalf("%s is not listed:\n%s", name, out.Stdout)
	return ""
}

// extractAgeKey pulls the first age public key out of some output.
func extractAgeKey(t *testing.T, text string) string {
	t.Helper()
	for _, field := range strings.Fields(text) {
		trimmed := strings.Trim(field, ",.\"'()")
		if strings.HasPrefix(trimmed, "age1") && len(trimmed) > 50 {
			return trimmed
		}
	}
	return ""
}
